version: "3"

services:
  nodejs:
    image: node:latest
    restart: always
    environment:
      VIRTUAL_HOST: graphql.docker
    working_dir: /srv
    command: npm run start
    expose:
      - 8080
    volumes:
      - ./src:/srv
    networks:
      - dev-network

networks:
  dev-network:
    external: true
