version: "3"

services:
  php:
    build: .
    restart: always
    environment:
      VIRTUAL_HOST: php.docker
    volumes:
      - ./src:/var/www/html/php/public
    networks:
      - dev-network

networks:
  dev-network:
    external: true
