version: "3"

services:
  postgresql:
    image: postgres
    restart: always
    environment:
      VIRTUAL_HOST: postgres.docker
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - dev-network

networks:
  dev-network:
    external: true
